### ISSUE TITLE
YOO I GOT IT TO WORK. Crash dont work tho

### ISSUE THREAD

**Issue by CoolScripter299** [efenatuyo/bloxflipPredictor#11]
fantastic bot, extremely accurate i love it, only problem is that crash doesnt work.

**Comment by efenatuyo** [comment]
What does it say

**Comment by CoolScripter299** [comment]
![Screenshot 2022-09-23 201045](https://user-images.githubusercontent.com/82603186/192071388-22f8dfbe-ffc7-4cd9-ba52-b7a1eb204561.png)

just stays stuck at this

**Comment by jacklolidk** [comment]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\user\Downloads\bloxflipPredictor-1.2.1\main.py", line 182, in crash
    if chan == True:
UnboundLocalError: local variable 'chan' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\bot.py", line 1347, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\core.py", line 986, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\discord\ext\commands\core.py", line 199, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnboundLocalError: local variable 'chan' referenced before assignment

**Comment by jacklolidk** [comment]
crash in cmd

**Comment by ttvbeghhf** [comment]
Mine wont start it js says invaild token or token isnt found i need help

**Comment by tricx0** [comment]
You just got the old Version Switch to this https://github.com/efenatuyo/bloxflipPredictor/releases/tag/2.3.2

**Comment by ttvbeghhf** [comment]
i did and it still says the same thing and im running it on repilt

**Comment by ttvbeghhf** [comment]
![image](https://user-images.githubusercontent.com/77454237/192296499-4be13800-e74a-42ff-80a1-90006de0afc3.png)
thats what its saying now
