### ISSUE TITLE
discord.ext.commands.bot: Ignoring exception in command mines

### ISSUE THREAD

**Issue by Puppotty** [efenatuyo/bloxflipPredictor#17]
when i do .mines i get this error:

Traceback (most recent call last):
  File "C:\Users\mpupp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\discord\ext\commands\core.py", line 190, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\mpupp\OneDrive\Desktop\bloxflipPredictor-2.2.1\main.py", line 80, in reg
    await mines(ctx, e)    #  Starts the mine predictor
  File "C:\Users\mpupp\OneDrive\Desktop\bloxflipPredictor-2.2.1\main.py", line 100, in mines
    output=c.minespredictor(msgo, bombs)
NameError: name 'c' is not defined

**Comment by Puppotty** [comment]
![image](https://user-images.githubusercontent.com/86609738/192101639-6090fc2e-01e2-4d0c-a6af-30660aa4ce2a.png)

**Comment by efenatuyo** [comment]
try the new update

**Comment by Puppotty** [comment]
im trying now, btw what do you recommend to put on "bombs", default is 1, what should i put to gt better results?

**Comment by efenatuyo** [comment]
1 is the best

**Comment by Puppotty** [comment]
ok now it works fine, ty!

**Comment by zPitachu** [comment]
@efenatuyo I have this same problem when i try to do mines, after typing amount of tiles this shows up



![image](https://user-images.githubusercontent.com/114113339/192106074-ff51c005-21d8-4d40-822f-28211d20aa44.png)
